/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "hello.h"

bool_t
xdr_Livro (XDR *xdrs, Livro *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->nome, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->codigo))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->preco))
		 return FALSE;
	return TRUE;
}
