/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "hello.h"

int *hello_1_svc(char **argp, struct svc_req *rqstp)
{
	static int result;

	/*
	 * insert server code here
	 */

	fprintf(stdout, "%s\n", *argp);
	fflush(stdout);

	return &result;
}

int *consulta_1_svc(Livro *argp, struct svc_req *rqstp)
{
	static int result;

	/*
	 * insert server code here
	 */

	fprintf(
			stdout,
			"Livro: %s, código %d, custa %f.\n",
			argp->nome,
			argp->codigo,
			argp->preco);
	fflush(stdout);

	return &result;
}
