/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _HELLO_H_RPCGEN
#define _HELLO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Livro {
	char *nome;
	int codigo;
	float preco;
};
typedef struct Livro Livro;

#define HELLOPROG 0x30090949
#define HELLOVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define HELLO 1
extern  int * hello_1(char **, CLIENT *);
extern  int * hello_1_svc(char **, struct svc_req *);
#define Consulta 2
extern  int * consulta_1(Livro *, CLIENT *);
extern  int * consulta_1_svc(Livro *, struct svc_req *);
extern int helloprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define HELLO 1
extern  int * hello_1();
extern  int * hello_1_svc();
#define Consulta 2
extern  int * consulta_1();
extern  int * consulta_1_svc();
extern int helloprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Livro (XDR *, Livro*);

#else /* K&R C */
extern bool_t xdr_Livro ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_HELLO_H_RPCGEN */
